package report;

public class Borrowing extends Report {
    private String bookTitle;
    private String borrowerId;
    private String dateBorrowed;
    private String dueDate;
    private String dateReturned;
    private String approvedById;
    private int timesRenewed;

    public Borrowing(String id, String generated_by, String generated_date,
                     String bookTitle, String borrowerId, String dateBorrowed,
                     String dueDate, String dateReturned, String approvedById,
                     int timesRenewed) {
        super(id, generated_by, generated_date);
        this.bookTitle = bookTitle;
        this.borrowerId = borrowerId;
        this.dateBorrowed = dateBorrowed;
        this.dueDate = dueDate;
        this.dateReturned = dateReturned;
        this.approvedById = approvedById;
        this.timesRenewed = timesRenewed;
    }

    public String getBookTitle() {
        System.out.println("getBookTitle() called, returning: " + bookTitle);
        return bookTitle;
    }

    public void setBookTitle(String bookTitle) {
        System.out.println("setBookTitle() called, setting to: " + bookTitle);
        this.bookTitle = bookTitle;
    }

    public String getBorrowerId() {
        System.out.println("getBorrowerId() called, returning: " + borrowerId);
        return borrowerId;
    }

    public void setBorrowerId(String borrowerId) {
        System.out.println("setBorrowerId() called, setting to: " + borrowerId);
        this.borrowerId = borrowerId;
    }

    public String getDateBorrowed() {
        System.out.println("getDateBorrowed() called, returning: " + dateBorrowed);
        return dateBorrowed;
    }

    public void setDateBorrowed(String dateBorrowed) {
        System.out.println("setDateBorrowed() called, setting to: " + dateBorrowed);
        this.dateBorrowed = dateBorrowed;
    }

    public String getDueDate() {
        System.out.println("getDueDate() called, returning: " + dueDate);
        return dueDate;
    }

    public void setDueDate(String dueDate) {
        System.out.println("setDueDate() called, setting to: " + dueDate);
        this.dueDate = dueDate;
    }

    public String getDateReturned() {
        System.out.println("getDateReturned() called, returning: " + dateReturned);
        return dateReturned;
    }

    public void setDateReturned(String dateReturned) {
        System.out.println("setDateReturned() called, setting to: " + dateReturned);
        this.dateReturned = dateReturned;
    }

    public String getApprovedById() {
        System.out.println("getApprovedById() called, returning: " + approvedById);
        return approvedById;
    }

    public void setApprovedById(String approvedById) {
        System.out.println("setApprovedById() called, setting to: " + approvedById);
        this.approvedById = approvedById;
    }

    public int getTimesRenewed() {
        System.out.println("getTimesRenewed() called, returning: " + timesRenewed);
        return timesRenewed;
    }

    public void setTimesRenewed(int timesRenewed) {
        System.out.println("setTimesRenewed() called, setting to: " + timesRenewed);
        this.timesRenewed = timesRenewed;
    }

    @Override
    public void displayReport() {
        System.out.println("Report ID: " + getId());
        System.out.println("Generated By: " + getGeneratedBy());
        System.out.println("Generated Date: " + getGeneratedDate());
        System.out.println("Book Title: " + bookTitle);
        System.out.println("Borrower ID: " + borrowerId);
        System.out.println("Date Borrowed: " + dateBorrowed);
        System.out.println("Due Date: " + dueDate);
        System.out.println("Date Returned: " + dateReturned);
        System.out.println("Approved By: " + approvedById);
        System.out.println("Times Renewed: " + timesRenewed);
    }
}
