package report;

public class Borrowing extends Report {
    private String bookTitle;
    private String borrowerId;
    private String dateBorrowed;
    private String dueDate;
    private int timesRenewed;

    public Borrowing(String id, String generatedBy, String generatedDate,
                     String bookTitle, String borrowerId, String dateBorrowed,
                     String dueDate) {
        super(id, generatedBy, generatedDate);
        this.bookTitle = bookTitle;
        this.borrowerId = borrowerId;
        this.dateBorrowed = dateBorrowed;
        this.dueDate = dueDate;
        this.timesRenewed = 0;
    }

    public String getBookTitle() {
        return bookTitle;
    }

    public void setBookTitle(String bookTitle) {
        this.bookTitle = bookTitle;
    }

    public String getBorrowerId() {
        return borrowerId;
    }

    public void setBorrowerId(String borrowerId) {
        this.borrowerId = borrowerId;
    }

    public String getDateBorrowed() {
        return dateBorrowed;
    }

    public void setDateBorrowed(String dateBorrowed) {
        this.dateBorrowed = dateBorrowed;
    }

    public String getDueDate() {
        return dueDate;
    }

    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

    public int getTimesRenewed() {
        return timesRenewed;
    }

    public void setTimesRenewed(int timesRenewed) {
        this.timesRenewed = timesRenewed;
    }

    public void extendDueDate(String newDueDate) {
        this.dueDate = newDueDate;
        this.timesRenewed++;
    }

    @Override
    public void displayReport() {
        System.out.println("Report ID: " + getId());
        System.out.println("Generated By: " + getGeneratedBy());
        System.out.println("Generated Date: " + getGeneratedDate());
        System.out.println("Book Title: " + bookTitle);
        System.out.println("Borrower ID: " + borrowerId);
        System.out.println("Date Borrowed: " + dateBorrowed);
        System.out.println("Due Date: " + dueDate);
        System.out.println("Times Renewed: " + timesRenewed);
    }

    @Override
    public String exportReport() {
        return String.format(
            "Borrowing Report\nID: %s\nGenerated By: %s\nDate: %s\nBook: %s\nBorrower: %s\nBorrowed On: %s\nDue Date: %s\nTimes Renewed: %d",
            getId(), getGeneratedBy(), getGeneratedDate(), bookTitle, borrowerId, dateBorrowed, dueDate, timesRenewed
        );
    }

    @Override
    public boolean isValid() {
        return getId() != null && !getId().isEmpty()
            && bookTitle != null && !bookTitle.isEmpty()
            && borrowerId != null && !borrowerId.isEmpty()
            && dueDate != null && !dueDate.isEmpty();
    }
}
