package report;

public class Recommendation extends Report {
    private String recommendedTo;
    private String recommendationText;

    public Recommendation(String id, String generated_by, String generated_date,
                          String recommendedTo, String recommendationText) {
        super(id, generated_by, generated_date);
        System.out.println("Recommendation constructor called with recommendedTo: " + recommendedTo + ", recommendationText: " + recommendationText);
        this.recommendedTo = recommendedTo;
        this.recommendationText = recommendationText;
    }

    public String getRecommendedTo() {
        System.out.println("getRecommendedTo() called, returning: " + recommendedTo);
        return recommendedTo;
    }

    public void setRecommendedTo(String recommendedTo) {
        System.out.println("setRecommendedTo() called, setting to: " + recommendedTo);
        this.recommendedTo = recommendedTo;
    }

    public String getRecommendationText() {
        System.out.println("getRecommendationText() called, returning: " + recommendationText);
        return recommendationText;
    }

    public void setRecommendationText(String recommendationText) {
        System.out.println("setRecommendationText() called, setting to: " + recommendationText);
        this.recommendationText = recommendationText;
    }

    @Override
    public void displayReport() {
        System.out.println("Report ID: " + getId());
        System.out.println("Generated By: " + getGeneratedBy());
        System.out.println("Generated Date: " + getGeneratedDate());
        System.out.println("Recommended To: " + recommendedTo);
        System.out.println("Recommendation: " + recommendationText);
    }
}
